version: '3'


services:


  motus: 
    
    build: 
      context: ./motus/
      dockerfile: Dockerfile
      
    ports: 
      - 3000:3000

  score: 
    
    build: 
      context: ./score/
      dockerfile: Dockerfile
      
    ports: 
      - 4000:4000


  auth:
    build:
      context: ./auth/
      dockerfile: Dockerfile
      
    ports: 
      - 8080:8080


  postgres:
    image: "postgres:latest"
    restart: always
    ports: 
      - 5432:5432
    container_name: postgres_data1
    volumes:
      - /var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=root_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres